### ISSUE TITLE
Windows master build has started to fail, good 

### ISSUE THREAD

**Issue by Karm** [graalvm/mandrel#264] opened 2021-06-23 14:20 UTC
## Good :heavy_check_mark: 
Graal: Revision: 03202086026f62bcffa137343df7658232dde09d
    refs/remotes/origin/graal/master
MX: Revision: c9fa6cf69424f1296ae44d06f582250418e8d6e2
    refs/remotes/origin/master

## Fails :x: 
Graal: Revision: ba1a28e354713d7a6d0406335080e0ccb7ce018b
    refs/remotes/origin/graal/master
MX:	Revision: fb36392d3c4d0168222dbe6d291b1c2825ae2a4d
    refs/remotes/origin/master

Full log: https://ci.modcluster.io/view/Mandrel/job/mandrel-master-windows-build/295/consoleText

```
IOError: [Errno 2] No such file or directory: 'C:\\workspace\\workspace\\mandrel-maste---90016775\\mandrel\\compiler\\mxbuild\\src\\org.graalvm.compiler.truffle.compiler.hotspot\\bin\\org\\graalvm\\compiler\\truffle\\compiler\\hotspot\\PluginReplacementNode_HotSpotTruffleSafepointLoweringSnippet_pendingHandshakeOffset.class'
java.net.SocketException: Connection reset
```

**Comment by zakkak** [comment] 2021-06-23 14:44
Thanks @Karm , started https://github.com/graalvm/mandrel/actions/runs/964716849 to see if it's reproducible on our GH workflow

**Comment by zakkak** [comment] 2021-06-23 15:23
The issue is not reproducible on github so it might be an issue with our Jenkins workflow.

1b41b6e708fe7a8373b6b5961b8ff774bda49f88 (latest graal/master) fails in https://ci.modcluster.io/view/Mandrel/job/mandrel-master-windows-build/296/ fails in but builds in https://github.com/graalvm/mandrel/actions/runs/964795483

**Comment by Karm** [comment] 2021-06-23 15:26
@zakkak Well, that is weird. I don't think anything changed there.

**Comment by zakkak** [comment] 2021-06-23 15:28
Is there any chance to have some stale state in the runner? i.e. some class or source files from previous runs?

**Comment by Karm** [comment] 2021-06-23 16:13
@zakkak There is a workspace cleanup https://github.com/graalvm/mandrel-packaging/blob/master/jenkins/jobs/mandrel_master_windows_build.groovy#L113 after build, but anything is possible as the host is not freshly provisoned for each job run. That said, this is the first occurrence of such particular issue tom my best knowledge. I will investigate it later and try the build manually on the host.

**Comment by zakkak** [comment] 2021-06-28 09:26
This is now fixed, the issue was related to using python 2 instead of python 3.

**Closed by zakkak** 2021-06-28 09:26 UTC
Labels: affects/21.2, bug
