### ISSUE TITLE
JDK 11.0.15+8-167-gc38229fb06, Mandrel 21.3: jdk.Target_java_io_ObjectStreamClass_Caches.localDesc

### ISSUE THREAD

**Issue by Karm** [graalvm/mandrel#372] opened 2022-04-12 19:21 UTC
It seems the merged #369 fails to build a native agent app with the latest JDK 11:

```
EBUG [OperatingSystem] Execute [./mandrel-java11-21.3.2.0-dev7e97bdc46c6/lib/svm/bin/native-image, --macro:native-image-agent-library] in /home/tester/workspace/mandrel-21-3-jdk11-latest-linux-amd64 with environment variables []
[libnative-image-agent:241908]    classlist:   1,248.35 ms,  0.96 GB
[libnative-image-agent:241908]        setup:     478.32 ms,  0.96 GB
Error: Type mismatch:
    interface java.util.concurrent.ConcurrentMap static java.util.concurrent.ConcurrentMap com.oracle.svm.core.jdk.Target_java_io_ObjectStreamClass_Caches.localDescs
    class java.io.ClassCache static final java.io.ClassCache java.io.ObjectStreamClass$Caches.localDescs
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
[libnative-image-agent:241908]      [total]:   1,798.53 ms,  0.96 GB
# Printing build artifacts to: /home/tester/workspace/mandrel-21-3-jdk11-latest-linux-amd64/mandrel-java11-21.3.2.0-dev7e97bdc46c6/lib/svm/macros/native-image-agent-library/../../../libnative-image-agent.build_artifacts.txt
Error: Image build request failed with exit status 1
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1558)
	at build.buildAgents(build.java:189)
	at build.main(build.java:171)
Caused by: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1543)
	at build.buildAgents(build.java:189)
	at build.main(build.java:171)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:404)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:179)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:119)
```

JDK used: jdk-11.0.15+8-167-gc38229fb06

**Comment by Karm** [comment] 2022-04-12 19:23
I don't see it in the Graal issues tracker. I'll try with Graal and see where it leads.

**Comment by Karm** [comment] 2022-04-12 19:24
@jerboaa The current ea, i.e. *11.0.15-beta+8-202204071807* is fine and builds O.K. with Mandrel 21.3 head.

**Comment by zakkak** [comment] 2022-04-13 07:42
@Karm the issue is triggered by https://github.com/openjdk/jdk11u-dev/commit/118ec6172ffdc204a196559babe7bd116ea33763 which is not merged to jdk11u yet, i.e., it won't land in 11.0.15 but in 11.0.16

I assume you are building OpenJDK from jdk11u-dev, right?

This issue seems like a duplicate of #371, I suggest closing this and updating #371 to include `affects/21.3` tag

**Comment by jerboaa** [comment] 2022-04-13 08:15
Yes, it's a duplicate of #371. Closing.

**Closed by jerboaa** 2022-04-13 08:15 UTC
Labels: bug
