### ISSUE TITLE
GraalVM 22.3.0-dev Quarkus native readiness tracker

### ISSUE THREAD

**Issue by jerboaa** [graalvm/mandrel#417] opened 2022-08-10 18:15 UTC
We are seeing some CI failures in quarkus native integration tests on the master branch (22.3.0-dev tree). This serves as a tracker for all issues in prep for the 22.3.0 release:

# Mandrel only (not seen with GraalVM CE):

https://github.com/quarkusio/quarkus/issues/27211 (Fixed with https://github.com/quarkusio/quarkus/pull/27225)

# GraalVM CE and Mandrel:

https://github.com/quarkusio/quarkus/issues/27232 (Fixed with https://github.com/quarkusio/quarkus/pull/27366)
https://github.com/quarkusio/quarkus/issues/27300 (Fixed with https://github.com/oracle/graal/pull/4997)
https://github.com/quarkusio/quarkus/issues/27791 (Fixed with https://github.com/quarkusio/quarkus/pull/27960)

**Comment by jerboaa** [comment] 2022-09-19 17:54
As of today there shouldn't be any more breakages for 22.3-dev as the kotlin issue got fixed too. I'll close this tomorrow if native integration tests look good.

**Comment by jerboaa** [comment] 2022-09-20 09:28
Yes, all kotlin related failures are gone now. Closing. See for example: https://github.com/graalvm/mandrel/actions/runs/3087363520

**Comment by zakkak** [comment] 2022-09-20 09:42
There seems to be a new issue with the `gradle` integration test caused by https://github.com/quarkusio/quarkus/pull/27728 and fixed by https://github.com/quarkusio/quarkus/pull/28084

**Comment by jerboaa** [comment] 2022-09-20 12:14
> There seems to be a new issue with the `gradle` integration test caused by [quarkusio/quarkus#27728](https://github.com/quarkusio/quarkus/pull/27728) and fixed by [quarkusio/quarkus#28084](https://github.com/quarkusio/quarkus/pull/28084)

Aha! Thanks faster than me.

**Comment by zakkak** [comment] 2022-09-22 13:18
Last issue fixed as well :)

**Closed as completed by zakkak** 2022-09-22 13:18 UTC
Labels: bug
