### ISSUE TITLE
Mandrel 20.2: Warning: Using an older version of the labsjdk-11

### ISSUE THREAD

**Issue by Karm** [graalvm/mandrel#125] opened 2020-09-03 13:41 UTC
Native image build spits this warning:

```
WARNING: Using an older version of the labsjdk-11.
```

Mandrel 20.2 is built with [OpenJDK 11.0.9+3 EA build](https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/tag/jdk-11.0.9%2B3).

As @zakkak  suggest, this is about the location of static libs. [Graal source](https://github.com/oracle/graal/blob/d77d41e182520cca871b0fdcc74aa37d29c37b83/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/c/NativeLibraries.java#L276-L296).

**Comment by Karm** [comment] 2020-09-03 13:43
The message is whitelisted in the TS for the time being:

```
2020-09-03 15:42:31.340 INFO  [o.g.t.i.u.Logs] (checkLog) build-and-run.log log for
   timezonesBakedIn contains whitelisted error: `WARNING: Using an older version of the labsjdk-11.'
```

**Comment by jerboaa** [comment] 2020-09-03 16:40
This is actually a backwards incompatible change and breaks the 20.1 mandrel build. There are a couple of ways to solve this:

* Produce Vanilla upstream OpenJDK artifacts with static-libs in the new location with a symlink to the new location at the old location (not really a portable solution).
* Remove the warning msg via a patch in mandrel distro
* Get the code looking for things in the new location backported to 20.1 mandrel.
* Do some tricks in mandrel-packaging to the base JDK depending on the mandrel version

Not sure what to do here. @galderz @zakkak Thoughts?

**Comment by zakkak** [comment] 2020-09-03 19:49
I vote the 3rd, I think backporting https://github.com/oracle/graal/commit/d7b5904db656d1313d6462a0034818dfccbbb69b should do the trick

**Comment by jerboaa** [comment] 2020-09-04 14:36
@zakkak we'd need to get the timing for this right, though. It's a big bang change and OpenJDK 11 changes and mandrel changes need to be coordinated well.

**Comment by zakkak** [comment] 2020-09-04 14:51
That's correct, but I don't think it's hard to achieve. We just have to test it with EA and once GA is out we merge the backport and create a new release (which we would anyway to get the latest GA OpenJDK in the mandrel release).

**Comment by galderz** [comment] 2020-09-09 08:10
Either 2 or 3 for me.

**Comment by jerboaa** [comment] 2020-09-09 14:07
OK. I've got a patch ready for vanilla OpenJDK. See https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/pull/10 We should pipeline a backport for the 20.1 mandrel branch and merge around the October OpenJDK 11 CPU timeline.

**Comment by jerboaa** [comment] 2020-09-14 16:34
@zakkak FYI: I'm working on a backport of https://github.com/oracle/graal/commit/d7b5904db656d1313d6462a0034818dfccbbb69b

**Comment by zakkak** [comment] 2020-09-14 19:25
> @zakkak FYI: I'm working on a backport of [oracle@d7b5904](https://github.com/oracle/graal/commit/d7b5904db656d1313d6462a0034818dfccbbb69b)

Nice, thanks for the heads up!

**Comment by zakkak** [comment] 2020-10-15 12:43
@Karm @jerboaa it looks like this is no longer needed
See https://github.com/oracle/graal/commit/ece265a89e6cfa8cd5f10881891f73661f5cc04f

**Comment by zakkak** [comment] 2020-10-15 13:14
FTR:
The warningg was added in https://github.com/oracle/graal/commit/2a1945d6e36e2f7c1bdc5756f30d72c5332f4f89 (which affects 20.2)
and later removed in https://github.com/graalvm/mandrel/commit/9a1f46d9e6c149ed9720666a66f9e18a7baa4c3e (which is expected to end up in 20.3)

**Comment by jerboaa** [comment] 2020-10-15 18:12
Thanks for the detective work, @zakkak. I believe moving to the new layout is for the better.

**Comment by zakkak** [comment] 2020-10-22 05:09
11.0.9-GA is now released and the issue is no longer present in either version

**Closed by zakkak** 2020-10-22 05:09 UTC
Labels: affects/20.1, affects/20.2, backport, bug
