### ISSUE TITLE
JFR: -H:+AllowVMInspection, Could not find target method: public long com.oracle.svm.jfr.Target_jdk_jfr_internal_JVM.getEpochAddress

### ISSUE THREAD

**Issue by Karm** [graalvm/mandrel#261] opened 2021-06-17 06:20 UTC
Building e.g. this app: [debug-symbols-smoke](https://github.com/Karm/mandrel-integration-tests/tree/master/apps/debug-symbols-smoke) to enable JFR:

```
mvn package
native-image -H:GenerateDebugInfo=1 -H:+PreserveFramePointer -H:-DeleteLocalSymbols -H:+AllowVMInspection -H:+ReportExceptionStackTraces -jar target/debug-symbols-smoke.jar target/debug-symbols-smoke
```
Causes:

```
[target/debug-symbols-smoke:662587]    classlist:     770.39 ms,  0.96 GB
[target/debug-symbols-smoke:662587]        setup:     372.58 ms,  0.96 GB
Error: Could not find target method: public long com.oracle.svm.jfr.Target_jdk_jfr_internal_JVM.getEpochAddress()
com.oracle.svm.core.util.UserError$UserException: Could not find target method: public long com.oracle.svm.jfr.Target_jdk_jfr_internal_JVM.getEpochAddress()
	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findOriginalMethod(AnnotationSubstitutionProcessor.java:734)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleMethodInAliasClass(AnnotationSubstitutionProcessor.java:366)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:338)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:310)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:266)
	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:968)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:900)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:571)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:497)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[target/debug-symbols-smoke:662587]      [total]:   1,175.87 ms,  0.96 GB
# Printing build artifacts to: /home/karm/workspaceRH/mandrel-integration-tests/apps/debug-symbols-smoke/target/debug-symbols-smoke.build_artifacts.txt
Error: Image build request failed with exit status 1
```
native-image used comes from Mandrel distribution of recent Graal master:  

```
Mandrel master-SNAPSHOT c03bfc33d5
OpenJDK used: 11.0.12-ea+5
```
The JDK used to build Mandrel comes from:  [Adopt jdk-11.0.12_5](https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/tag/jdk-11.0.12%2B5).

I will keep the tarball over here for some time: [mandrel-java11-linux-amd64-21.2.0-devc03bfc33d5.tar.gz](https://ci.modcluster.io/view/Mandrel/job/mandrel-master-linux-build/299/artifact/mandrel-java11-linux-amd64-21.2.0-devc03bfc33d5.tar.gz)

**Comment by Karm** [comment] 2021-06-17 06:22
Ping @jiekang

**Comment by Karm** [comment] 2021-06-17 07:26
(sent an invite to jiekang)

**Comment by jiekang** [comment] 2021-06-17 14:10
This is caused by an API removal from JVM.java that came from the backport of [JDK-8257621](https://bugs.openjdk.java.net/browse/JDK-8263882). We'll need to update the code to handle this change. 

The base fix is very straightforward but needs some further adjustment. The StringPool is not yet implemented in SubstrateVM, so it must not be used by the Java EventWriter. Unfortunately the Java and native code after this backport doesn't respect the API described here:

```
     * @return true, if the string was successfully added.
     */
    public static native boolean addStringConstant(long id, String s);
```

Returning false would previously cause the EventWriter to emit the string. Now the native code always returns true:

```
jboolean JfrStringPool::add(jlong id, jstring string, JavaThread* jt) {
  assert(jt != NULL, "invariant");
  JfrStringPoolWriter writer(jt);
  writer.write(id);
  writer.write(string);
  writer.inc_nof_strings();
  return JNI_TRUE;
}
```

And the Java side ignores the return value and always uses the StringPool:

```
            synchronized(SimpleStringIdPool.class) {
                JVM.addStringConstant(sid, s);
                currentSizeUTF16 += s.length();
            }
            return sid;
```

Previously it would use `-1` as the failure state e.g. `boolean success = JVM.addStringConstant ... if (!success) return -1`

Because we don't have the StringPool implemented in SubstrateVM, we need this failure state. The most simple solution is to also substitute `jdk.jfr.internal.StringPool` method `static long addString(String s)` to always return -1. The EventWriter will then always write out the string in it's `putString` method (see `l > 0` if statement):

```
jdk.jfr.internal.EventWriter:
    ...
    public void putString(String s, StringPool pool) {
        if (s == null) {
            putByte(RecordingInput.STRING_ENCODING_NULL);
            return;
        }
        int length = s.length();
        if (length == 0) {
            putByte(RecordingInput.STRING_ENCODING_EMPTY_STRING);
            return;
        }
        if (length > StringPool.MIN_LIMIT && length < StringPool.MAX_LIMIT) {
            long l = StringPool.addString(s);
            if (l > 0) {
                putByte(RecordingInput.STRING_ENCODING_CONSTANT_POOL);
                putLong(l);
                return;
            }
        }
        putStringValue(s);
        return;
    }
```

**Comment by zakkak** [comment] 2021-06-17 14:57
@jiekang can you please have a look at https://github.com/zakkak/mandrel/commit/12c66d8b943b130fb1b7da6da379485e7a619a7c?

I am not able to test it yet since after applying this patch it hits #262

**Comment by jiekang** [comment] 2021-06-17 15:28
@zakkak it looks sound to me. Is it common to carry minor release differences like that? I thought each native-image release would target a specific release: *only* 11.0.12 or *only* 11.0.11, etc. I don't like the sound of maintaining more than just major release differences :|

On a random note, I guess we're fortunate that the OpenJDK 11 backport missed removing the unused `unsafe` field so you don't need two separate StringPool substitution classes for that `@Alias` annotation :P

**Comment by jerboaa** [comment] 2021-06-17 15:39
> @zakkak it looks sound to me. Is it common to carry minor release differences like that? I thought each native-image release would target a specific release: _only_ 11.0.12 or _only_ 11.0.11, etc. I don't like the sound of maintaining more than just major release differences :|

It's quite common. The intention is merely to support various JDKs for *building*. Think gate-tests etc. We've had to do that sort of conditional substitution a fair bit. The actual releases are a different story and actually include the JDK it got built with.

**Comment by zakkak** [comment] 2021-06-23 11:56
This is now fixed by https://github.com/oracle/graal/commit/b9fad3c8526c333caaf201e605e003266b315027

**Closed by zakkak** 2021-06-23 11:56 UTC
Labels: affects/21.2, bug

**Comment by jerboaa** [comment] 2021-06-23 12:09
@zakkak We still would need for https://github.com/oracle/graal/commit/b9fad3c8526c333caaf201e605e003266b315027 to go into 21.2 release branch, right?

**Comment by zakkak** [comment] 2021-06-23 13:17
That's correct, my understanding is that it will be part of 21.2.
Let's see if @christianhaeubl can confirm this.

**Comment by christianhaeubl** [comment] 2021-06-23 14:07
@jerboaa, @zakkak: https://github.com/oracle/graal/commit/b9fad3c8526c333caaf201e605e003266b315027 is already part of the 21.2 release branch.

**Comment by jerboaa** [comment] 2021-06-23 14:32
@christianhaeubl That's fantastic! Thanks for the heads-up.

Do you know if there is there a way for us to determine ourselves? I don't see a public `release/graal-vm/21.2` branch in https://github.com/oracle/graal/

**Comment by christianhaeubl** [comment] 2021-06-23 14:34
I don't think that the release branches are synced to GitHub at the moment /cc @gilles-duboscq

**Comment by gilles-duboscq** [comment] 2021-06-23 17:02
Indeed, just reviewed the PR that adds mirroring for those branches so they should be available soon.

**Comment by jerboaa** [comment] 2021-06-23 17:12
@gilles-duboscq @christianhaeubl Thank you! Much appreciated.
