### ISSUE TITLE
Mandrel 23.0 JDK 21,  build failure

### ISSUE THREAD

**Issue by Karm** [graalvm/mandrel#527] opened 2023-07-09 18:02 UTC
Logged on Windows, the same on Linux.

```
Processor com.oracle.svm.processor.AutomaticallyRegisteredImageSingletonProcessor matches [] and returns true.
Round 4:
	input files: {}
	annotations: []
	last round: true
C:\workspace\workspace\mandrel-23-0----7fb250f3\JDK_RELEASE\ea\JDK_VERSION\21\LABEL\w2k19\mandrel\substratevm\src\com.oracle.svm.core\src\com\oracle\svm\core\jdk\JavaLangSubstitutions.java:703: error: cannot find symbol
@TargetClass(java.lang.Compiler.class)
                      ^
  symbol:   class Compiler
  location: package java.lang
[total 4499ms]
1 error
Result = 1
```

**Comment by jerboaa** [comment] 2023-07-10 08:38
This is caused by the removal of `java.lang.Compiler` class: https://bugs.openjdk.org/browse/JDK-8205129

**Comment by zakkak** [comment] 2023-07-25 11:32
23.0 is not expected to work with JDK 21, it's only meant to build with JDK 17 and 20.

On `graal/master` (aka 23.1-dev) [this is fixed](https://github.com/oracle/graal/commit/e451cff6e2e0498c348b764a9c060d3c29f8e164).

Closing as not planned.

**Closed as not planned by zakkak** 2023-07-25 11:32 UTC
Labels: bug
