### ISSUE TITLE
JDK 11.0.15/Mandrel 22.1: Type mismatch: interface java.util.concurrent.ConcurrentMap...

### ISSUE THREAD

**Issue by Karm** [graalvm/mandrel#371] opened 2022-04-04 14:35 UTC
## Passes:
JDK: jdk-11.0.15+7-96-g358fc5ac6b
Mandrel: 22.1 02f1c914d45

## Fails:
JDK: jdk-11.0.15+8-126-g3cf4e70ddd
Mandrel: 22.1 9915eb48bfb

```
==========================================================
GraalVM Native Image: Generating 'libnative-image-agent' (shared library)...
==========================================================

[1/7] Initializing...                                                                                    (0.0s @ 0.07GB)
Error: Type mismatch:
    interface java.util.concurrent.ConcurrentMap static java.util.concurrent.ConcurrentMap com.oracle.svm.core.jdk.Target_java_io_ObjectStreamClass_Caches.localDescs
    class java.io.ClassCache static final java.io.ClassCache java.io.ObjectStreamClass$Caches.localDescs
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
```

I will run the bisector to get to the actual change that triggered it...

**Comment by jerboaa** [comment] 2022-04-11 08:20
This looks like a duplicate of https://github.com/oracle/graal/issues/4477

**Comment by zakkak** [comment] 2022-04-13 07:45
Marking this as as `affects/21.3` and `affects/22.2` as the issue is triggered by

* https://github.com/openjdk/jdk11u-dev/commit/118ec6172ffdc204a196559babe7bd116ea33763 which is not merged to jdk11u yet, i.e., it won't land in 11.0.15 but in 11.0.16
* https://github.com/openjdk/jdk17u-dev/commit/7d132f5e5e2f8d27db82dd29bfdbc24677733b65 which is not merged to jdk17u yet, i.e., it won't land in 17.0.3 but in 17.0.4

As a result the issue will not affect the 22.1 and 21.3.2 releases, but the 22.2 and 21.3.3 releases.

**Comment by zakkak** [comment] 2022-05-10 07:05
Fixed upstream by https://github.com/oracle/graal/pull/4485

**Closed by zakkak** 2022-05-10 07:05 UTC
Labels: bug, pending upstream, affects/21.3, affects/22.2
